project_id = "oxszjnxqwomlbotooqbh"

[database]
# deixe as outras configurações como estão

[functions]
# Configura opções globais se existirem

[functions.setup-admin]
verify_jwt = false

[functions.send-delivery-codes]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false